goodplace/goodplace/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'goodplace.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^places/', include('places.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
)

goodplace/places/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    
    url(r'^propose/(?P<prop_id>[0-9]+)/$', views.propose, name='propose'),

    url(r'^proplist/$', views.proplist, name='proplist'),

    url(r'^newad/$', views.newad, name='newad')
]

goodplace/places/models.py
from django.forms.models import modelform_factory
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Props(models.Model):
    props_title = models.CharField(max_length=200)
    props_city = models.CharField(default="city", max_length=200)
    props_street = models.CharField(default="street", max_length=200)
    props_home = models.IntegerField(default=1)
    props_place = models.IntegerField(default=1)
    props_sleepplace = models.IntegerField(default=1)
    props_rating = models.FloatField(default=0)
    props_state = models.BooleanField(default=False)
    props_price = models.IntegerField(default=0)
    props_postfix = models.CharField(default="mes", max_length=20)
    props_authorname = models.CharField(default="ivan", max_length=20)
    props_authorlastname = models.CharField(default="ivanov", max_length=20)
    props_authorpatronymic = models.CharField(default="ivanovich", max_length=20)
    props_authorphone = models.IntegerField(default=0)
    props_howater = models.BooleanField(default=False)
    props_internet = models.BooleanField(default=False)
    props_washmachine = models.BooleanField(default=False)
    props_furniture = models.BooleanField(default=False)
    props_linens = models.BooleanField(default=False)
    props_utensils = models.BooleanField(default=False)
    props_microwave = models.BooleanField(default=False)
    props_kids = models.BooleanField(default=False)
    props_pets = models.BooleanField(default=False)
    props_addinfo = models.TextField(default="text")
    pub_date = models.DateTimeField('date published')

class Photos(models.Model):
	photoprop = models.ForeignKey(Props)
	props_photourl = models.CharField(default="/static/img/photoplace/default.jpg", max_length=200)

PropsForm = modelform_factory(Props, fields=('props_title', 'props_city'))

# class PropsForm(ModelForm):
#     class Meta:
#         model = Props
#         fields = ['props_title', 'props_city', 'props_street', 'props_home', 'props_place', 'props_sleepplace', 'props_rating', 'props_state', 'props_price', 'props_postfix', 'props_authorname', 'props_authorlastname', 'props_authorpatronymic', 'props_authorphone', 'props_howater', 'props_internet', 'props_washmachine', 'props_furniture', 'props_linens', 'props_utensils', 'props_microwave', 'props_kids', 'props_pets', 'props_addinfo', 'pub_date']

goodplace/places/views.py
from django.forms.models import modelform_factory
from django.shortcuts import render_to_response 
from django.http import HttpResponse
from django.template import RequestContext, loader
import datetime
from .models import  Props, Photos

def index(request):
    template = loader.get_template('index.html')
    context = RequestContext(request, {
        
    })
    return HttpResponse(template.render(context))

def propose(request, prop_id):
    props = Props.objects.get(pk=prop_id)
    propPhotos = Photos.objects.filter(photoprop=props)
    template = loader.get_template('propose.html')
    context = RequestContext(request, {
        'props': props,
        'prop_id': prop_id,
        'propPhotos': propPhotos
    })
    return HttpResponse(template.render(context))

def proplist(request):
    props = Props.objects.order_by('-pub_date')
    template = loader.get_template('proplist.html')
    context = RequestContext(request, {
        'props': props
    })
    return HttpResponse(template.render(context))

def newad(request):
    propsFormSet = modelform_factory(Props, fields=('props_title', 'props_city', "pub_date"))
    template = loader.get_template('newad.html')
    if request.method == 'POST':
        formset = propsFormSet(request.POST)
        print formset.is_valid()
        today = datetime.date.today().isoformat()
        if formset.is_valid():
            formset.save()
    else:
        formset = propsFormSet()
    return render_to_response("newad.html", {
        "formset": formset,
        "today": today
    },
        RequestContext(request)
    )

goodplace/goodplace/templates/base.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Good Place</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

goodplace/places/templates/index.html
<!DOCTYPE html>
<!--[if lte IE 7]> <html class="no-js ie67 ie" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 ie" lang="en"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9 ie" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
    <head>
      <meta charset="utf-8" />
      <title>Good Place</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="stylesheet" href="{{ STATIC_URL }}css/goodplace.all.css" />
      <!-- <link rel="stylesheet" href="static/css/angrycitizen.print.css" media="print"> -->
      <!--[if IE]><link rel="stylesheet" type="text/css" href="static/css/goodplace.ie.css"><![endif]-->
      <link rel="icon" type="image/x-icon" sizes="16x16" href="favicon.ico" />
      <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
      <script>
        document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
      </script>
  	</head>
  	<body>

  <aside class="modal modal-lodin">
	<div class="modal-content-wrapper">
		<header class="modal-header">
			<div class="modal-close">x</div>
			<div class="modal-title">Вход</div>
			<div class="modal-tip">войдите на сайт или <a href="#">зарегестрируйтесь</a></div>
		</header>
		<form class="modal-form">
			<ul class="modal-list">
				<li class="modal-list_item">
					<label for="login" class="modal-label">Логин:</label>
					<input type="text" class="goodplace-input modal-input" name="login">
				<li class="modal-list_item">
					<label for="password" class="modal-label">Пароль:</label>
					<input type="password" class="goodplace-input modal-input" name="password">
					<div class="modal-tip-bottom">
						<a href="#">Забыли пароль?</a>
					</div>
				<li class="modal-list_item">
					<input type="submit" class="goodspace-submit modal-submit" value="Войти">
			</ul>
		</form>
		
	</div>
</aside>  		
 	<header class="l-header">
      	<div class="l-restrictor l-restrictor__header">
        	<div class="header-logo">
        		<a href="/"><img src="{{ STATIC_URL }}img/header-logo.jpg" alt="good place"></a>
        	</div>
          <div class="header-description">На этом сайте вы сможете найти жилье для аренды на территории <strong>АР Крым</strong></div>
        	<div class="header-newad"><a href="/places/newad/" class="header-newad_link">Подать объявление</a></div>
        	<div class="header-login">
        		<a href="login.html" class="header-login_link">Вход</a>
        	</div>
      	</div>
	</header>
    <section class="l-section">
      <div class="l-restrictor">
        <div class="home-tip">Все просто:</div>
        <div class="home-tip-mobile">Найти жилье:</div>
        <ul class="home-guide">
          <li class="home-guide_item home-guide_item__find">найдите объявление
          <li class="home-guide_item home-guide_item__call">свяжитесь с владельцем объявления
          <li class="home-guide_item home-guide_item__deal">совершите сделку
        </ul>
        <div class="home-seasch-wrapper">
          <input class="home-search" type="text" placeholder="Поиск...">
          <div class="home-search-btn"></div>
        </div>

        <div class="home-krim-wrapper">
          <img src="{{ STATIC_URL }}img/krim.jpg" alt="крым аренда" class="home-krim">
        </div>
      </div>
    </section>
    

 
	<footer class="l-footer">
		<div class="l-restrictor">
			<div><a href="email:psr1919plus21@gmail.com" class="footer-author">psr1919plus21@gmail.com</a></div>
			<div class="footer-year">2015</div>	
		</div>
	</footer>
	<script src="{{ STATIC_URL }}js/jquery.js"></script>
	<script src="{{ STATIC_URL }}js/goodspace.handler.js"></script>
 </body>
</html> 

goodplace/places/templates/newad.html
<!DOCTYPE html>
<!--[if lte IE 7]> <html class="no-js ie67 ie" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 ie" lang="en"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9 ie" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
    <head>
      <meta charset="utf-8" />
      <title>Good Place</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.rating.css" />
      <link rel="stylesheet" href="{{ STATIC_URL }}css/goodplace.all.css" />
      <!-- <link rel="stylesheet" href="static/css/angrycitizen.print.css" media="print"> -->
      <!--[if IE]><link rel="stylesheet" type="text/css" href="static/css/goodplace.ie.css"><![endif]-->
      <link rel="icon" type="image/x-icon" sizes="16x16" href="favicon.ico" />
      <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
      <script>
        document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
      </script>
  	</head>
  	<body>

  <aside class="modal modal-lodin">
	<div class="modal-content-wrapper">
		<header class="modal-header">
			<div class="modal-close">x</div>
			<div class="modal-title">Вход</div>
			<div class="modal-tip">войдите на сайт или <a href="#">зарегестрируйтесь</a></div>
		</header>
		<form class="modal-form">
			<ul class="modal-list">
				<li class="modal-list_item">
					<label for="login" class="modal-label">Логин:</label>
					<input type="text" class="goodplace-input modal-input" name="login">
				<li class="modal-list_item">
					<label for="password" class="modal-label">Пароль:</label>
					<input type="password" class="goodplace-input modal-input" name="password">
					<div class="modal-tip-bottom">
						<a href="#">Забыли пароль?</a>
					</div>
				<li class="modal-list_item">
					<input type="submit" class="goodspace-submit modal-submit" value="Войти">
			</ul>
		</form>
		
	</div>
</aside>  		
 	<header class="l-header">
      	<div class="l-restrictor l-restrictor__header">
        	<div class="header-logo">
        		<a href="/places/"><img src="{{ STATIC_URL }}img/header-logo.jpg" alt="good place"></a>
        	</div>
          <div class="header-description">На этом сайте вы сможете найти жилье для аренды на территории <strong>АР Крым</strong></div>
        	<div class="header-newad"><a href="newad.html" class="header-newad_link">Подать объявление</a></div>
        	<div class="header-login">
        		<a href="login.html" class="header-login_link">Вход</a>
        	</div>
      	</div>
	</header>
    <section class="l-section">
      <div class="l-restrictor">
        <div class="home-tip">Новое объявленddие</div>
        <form method="POST" action="" class="newad-form">
          {% csrf_token %} 
          <!-- {% for form in formset %}
              {{form}}
          {% endfor %} -->
          <input id="id_pub_date" name="pub_date" type="hidden" value="{{ today }}">
          <ul class="newad-list">
            <li class="newad-list_item">
              <label  class="newad-label" required>Заголовок объявления</label>
              <div class="newad-content">
                <input id="id_props_title" name="props_title" type="text" class="goodplace-input newad-input" placeholder="Двухкомнатная квартира">
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Фотографии</label>
              <div class="newad-content">
                <input name="propose-photo" type="file" class="goodplace-file newad-input-file" >
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Цена</label>
              <div class="newad-content">
                <input name="propose-price" type="text" class="goodplace-input newad-price_price" placeholder="1000">
                <span class="newad-price_postfix">рублей</span>
                <select name="propose-price-period" id="price-period" class="goodplace-select newad-price_period">
                  <option value="сут.">посуточно</option>
                  <option value="мес.">помесячно</option>
                </select>
              </div>
            
            <li class="newad-list_item">
              <label class="newad-label"  required>Имя</label>
              <div class="newad-content">
                <input type="text" class="goodplace-input newad-input"  placeholder="Иван">
              </div>

            <li class="newad-list_item">
              <label class="newad-label"  required>Фамилия</label>
              <div class="newad-content">
                <input type="text" class="goodplace-input newad-input" name="propose-lastname" placeholder="Иванов">
              </div>

            <li class="newad-list_item">
              <label class="newad-label">Отчество</label>
              <div class="newad-content">
                <input type="text" class="goodplace-input newad-input" name="propose-patronymic" placeholder="Константинопольский">
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Мейл</label>
              <div class="newad-content">
                <input type="email" class="goodplace-input newad-input" name="propose-email" placeholder="yourmail@gmail.com">
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Телефон</label>
              <div class="newad-content">
                <input type="tel" class="goodplace-input newad-input" name="propose-phone" placeholder="79781231122">
              </div>

            <li class="newad-list_item">
              <label class="newad-label">Дом. телефон</label>
              <div class="newad-content">
                <input type="tel" class="goodplace-input newad-input" name="propose-phonehome" placeholder="223311">
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Адрес</label>
              <div class="newad-content">
                <select name="props_city" id="id_props_city" class="goodplace-select newad-geo_city">
                  <option value="" disabled selected>Город</option>
                  <option value="Севастополь">Севастополь</option>
                  <option value="Евпатория">Евпатория</option>
                </select>
                <input type="text" class="goodplace-input newad-input-siblings" name="propose-street" placeholder="Улица">
                <input type="text" class="goodplace-input newad-input-siblings" name="propose-home" placeholder="Дом">
                <input type="text" class="goodplace-input newad-input-siblings" name="propose-place" placeholder="Квартира">
                <input type="text" class="goodplace-input newad-input-siblings" name="propose-floor" placeholder="Этаж">
                <input type="text" class="goodplace-input newad-input-siblings" name="propose-floor-count" placeholder="Всего этажей в доме">
              </div>
            
            <li class="newad-list_item">
              <label class="newad-label" required>Спальных мест</label>
              <div class="newad-content">
                <select name="newad-sleepplaces" id="newad-sleepplaces" class="goodplace-select newad-sleepplaces">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                </select>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Горячая вода</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="hot-watter" val="true"> Есть</label>
                <label class="newad-content_label"><input type="radio" name="hot-watter" val="false"> Нет</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Интернет</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="internet" val="true"> Есть</label>
                <label class="newad-content_label"><input type="radio" name="internet" val="false"> Нет</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Стиральная машинка</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="wash-mashine" val="true"> Есть</label>
                <label class="newad-content_label"><input type="radio" name="wash-mashine" val="false"> Нет</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>СВЧ печь</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="microvave" val="true"> Есть</label>
                <label class="newad-content_label"><input type="radio" name="microvave" val="false"> Нет</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Постельное белье</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="linens" val="true"> Есть</label>
                <label class="newad-content_label"><input type="radio" name="linens" val="false"> Нет</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Мебель</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="furniture" val="true"> С мебелью</label>
                <label class="newad-content_label"><input type="radio" name="furniture" val="false"> Без мебели</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Посуда</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="utensils" val="true"> С посудой</label>
                <label class="newad-content_label"><input type="radio" name="utensils" val="false"> Без посуды</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Дети</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="childrens" val="true"> Можно</label>
                <label class="newad-content_label"><input type="radio" name="childrens" val="false"> Нельзя</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label" required>Домашние животные</label>
              <div class="newad-content">
                <label class="newad-content_label"><input type="radio" name="pets" val="true"> Можно</label>
                <label class="newad-content_label"><input type="radio" name="pets" val="false"> Нельзя</label>
              </div>

            <li class="newad-list_item">
              <label class="newad-label">Дополнительная информация</label>
              <div class="newad-content">
                <textarea class="goodplace-textarea newad-input-textarea" name="propose-additional-info" id="propose-additional-info" placeholder="Введите любую дополнительную информацию"></textarea>
              </div>

            <li class="newad-list_item">
              <input type="submit" class="goodspace-submit newad-submit" value="Опубликовать объявление">   
          </ul>  
         </form>
       
      </div>
    </section>
    

 
	<footer class="l-footer">
		<div class="l-restrictor">
			<div><a href="email:psr1919plus21@gmail.com" class="footer-author">psr1919plus21@gmail.com</a></div>
			<div class="footer-year">2015</div>	
		</div>
	</footer>
	<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/jquery.js"></script>
	<script src="{{ STATIC_URL }}js/goodspace.handler.js"></script>
	<script type="text/javascript">
		
		$.get( "http://geocode-maps.yandex.ru/1.x/?geocode=Евпатория+Полупанова+40", function( data ) {
			mapCenter = $(data).find("pos")[0].textContent.split(" ");
			console.log($(data));
			
			var myMap;
		 	ymaps.ready(init); // Ожидание загрузки API с сервера Яндекса
		 	
		  	function init () {
		  		console.log(mapCenter);
		    	myMap = new ymaps.Map("map", {
			      center: mapCenter.reverse(), // Координаты центра карты
			      zoom:16 // Zoom
		    	});
		  	}
		});

	  
	</script>
 </body>
</html> 

goodplace/places/templates/proplist.html
{% if props %}
    <ul>
    {% for props in props %}
        <li><a href="../propose/{{ props.id }}/">{{ props.props_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}